variable "aws_region" {}
variable "vpc_cidr" {}
variable "public_subnet_1" {}
variable "public_subnet_2" {}
variable "private_subnet_1" {}
variable "private_subnet_2" {}
variable "az_1" {}
variable "az_2" {}
variable "execution_role_arn" {}
variable "db_username" {}
variable "db_password" {}
variable "db_name" {}