#!/usr/bin/env python3
"""
Generates db/seed/seed.sql with deterministic pseudo-random data for the
hotel_bookings and booking_events tables.

Usage:
    python3 generate_seed.py > seed.sql
    (a pre-generated seed.sql is already committed, so this is only needed
    if you want to regenerate it with different volume/parameters)
"""
import random
import uuid
import json
from datetime import datetime, timedelta

random.seed(42)  # deterministic output across runs

NUM_BOOKINGS = 160          # comfortably over the required 100
NUM_ORGS = 6
CITIES = ["delhi", "mumbai", "bengaluru", "chennai", "hyderabad", "pune"]
STATUSES = ["confirmed", "pending", "cancelled", "completed", "refunded"]
EVENT_TYPES = ["created", "payment_received", "checked_in", "checked_out", "cancelled"]

ORG_IDS = [str(uuid.uuid4()) for _ in range(NUM_ORGS)]

def esc(s: str) -> str:
    return s.replace("'", "''")

def random_timestamp_within_days(days: int) -> datetime:
    now = datetime.utcnow()
    delta_seconds = random.randint(0, days * 24 * 3600)
    return now - timedelta(seconds=delta_seconds)

lines = []
lines.append("-- seed.sql")
lines.append("-- Auto-generated by generate_seed.py (seeded RNG, deterministic).")
lines.append("-- Seeds hotel_bookings across multiple cities/orgs/statuses, plus")
lines.append("-- booking_events for a subset of bookings.")
lines.append("")
lines.append("BEGIN;")
lines.append("")

booking_ids = []
booking_rows = []

for i in range(NUM_BOOKINGS):
    booking_id = str(uuid.uuid4())
    booking_ids.append(booking_id)

    org_id = random.choice(ORG_IDS)
    city = random.choice(CITIES)
    hotel_id = f"HTL-{random.randint(1000, 1999)}"

    # Skew ~40% of rows into the last 30 days so the optimized query has
    # meaningful data to aggregate, while the rest spans up to a year back.
    if random.random() < 0.4:
        created_at = random_timestamp_within_days(30)
    else:
        created_at = random_timestamp_within_days(365)

    checkin = created_at.date() + timedelta(days=random.randint(1, 60))
    checkout = checkin + timedelta(days=random.randint(1, 7))
    amount = round(random.uniform(1500, 45000), 2)
    status = random.choice(STATUSES)

    booking_rows.append(
        "  ('{id}', '{org}', '{hotel}', '{city}', DATE '{checkin}', DATE '{checkout}', "
        "{amount}, '{status}', TIMESTAMP '{created_at}')".format(
            id=booking_id,
            org=org_id,
            hotel=esc(hotel_id),
            city=esc(city),
            checkin=checkin.isoformat(),
            checkout=checkout.isoformat(),
            amount=f"{amount:.2f}",
            status=status,
            created_at=created_at.strftime("%Y-%m-%d %H:%M:%S"),
        )
    )

lines.append(
    "INSERT INTO hotel_bookings "
    "(id, org_id, hotel_id, city, checkin_date, checkout_date, amount, status, created_at)\nVALUES"
)
lines.append(",\n".join(booking_rows) + ";")
lines.append("")

# Booking events for ~70% of bookings, 1-4 events each
event_rows = []
for booking_id in booking_ids:
    if random.random() > 0.7:
        continue
    num_events = random.randint(1, 4)
    base_time = random_timestamp_within_days(30)
    for j in range(num_events):
        event_type = random.choice(EVENT_TYPES)
        event_time = base_time + timedelta(hours=j * random.randint(1, 12))
        payload = json.dumps({"source": "seed-script", "sequence": j + 1})
        event_rows.append(
            "  ('{booking_id}', '{event_type}', '{payload}'::jsonb, TIMESTAMP '{created_at}')".format(
                booking_id=booking_id,
                event_type=event_type,
                payload=payload.replace("'", "''"),
                created_at=event_time.strftime("%Y-%m-%d %H:%M:%S"),
            )
        )

lines.append(
    "INSERT INTO booking_events (booking_id, event_type, payload, created_at)\nVALUES"
)
lines.append(",\n".join(event_rows) + ";")
lines.append("")
lines.append("COMMIT;")
lines.append("")

print("\n".join(lines))
